export * from "./generated/api";
// NOTE: this barrel is regenerated by `pnpm codegen` in lib/api-spec, which
// re-adds `export * from "./generated/types"`. That wildcard makes the barrel
// ambiguous because some type names (e.g. GetOrderParams) also exist as zod
// schemas in ./generated/api, producing TS2308. scripts/fix-api-zod-barrel.ts
// strips the wildcard after codegen; keep re-exporting types explicitly below.
export type {
  AccountLinkInput,
  AccountLinkResult,
  AccountOrder,
  BadRequestResponse,
  ContactMessageCreated,
  ContactMessageCreatedStatus,
  ContactMessageInput,
  ContactMessageInputSubject,
  Country,
  CountryDetail,
  Error,
  EsimStatusResult,
  EsimStatusResultState,
  HealthStatus,
  ListCountriesParams,
  MaxPriceCentsParameter,
  NotFoundResponse,
  Order,
  OrderCreated,
  OrderInput,
  PaymentConfirmation,
  PaymentConfirmationResult,
  Plan,
  RegionParameter,
  SearchParameter,
  UnauthorizedResponse,
  WebhookInput,
  WebhookInputPayload,
  WebhookResult,
} from "./generated/types";
